import React, { useState } from 'react';

import * as Styled from './styles';
import styles from '../../styles/Home.module.css';

import Head from 'next/head';
import Header from '../../components/Header';
import Navbar from '../../components/Navbar';
import Footer from '../../components/Footer';

// standard layout for every page, contains header, navbar, footer and general styles
export default function Layout({ children }) {
  // const [search, setSearch] = useState('');
  // const [products, setProducts] = useState([]);

  // const handleSubmit = (e) => {
  //   setSearch(e.target.value);
  // };
  // const filteredProducts = !search
  //   ? products
  //   : products.filter((product) =>
  //       product.title.toLowerCase().includes(search.toLowerCase())
  //     );

  return (
    <Styled.Wrapper>
      <div className={styles.container}>
        <Head>
          <title>Yannecks SHOOOP DEVOOP</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
          <link
            rel='stylesheet'
            href='https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css'
            integrity='sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3'
          />
        </Head>

        <header className={styles.header}>
          <Header />
          <Navbar />
        </header>
        {children}
        <Footer />
      </div>
    </Styled.Wrapper>
  );
}
