export const contactText = {
  german: {
    contactTitle: 'Wir sind immer für dich da!',
    contactDescription: `Du has etwas auf dem Herzen? Lass es uns wissen und schreib uns eine
        Nachricht. Füll dazu einfach das Formular unten aus und ab geht die
        Post!`,
    emailTitle: 'E-Mail Adresse',
    emailPh: 'Deine E-Mail Adresse...',
    fornameTitle: 'Vorname',
    fornamePh: 'Vorname',
    surnameTitle: 'Nachname',
    surnamePh: 'Nachname',
    requestTitle: 'Dein Anliegen',
    sendBtn: 'Abschicken',
    serviceTitle: 'Kundenservice',
    serviceSubtitle: 'Das hat alles nichts gebracht?',
    secSubtitle: 'Wir sind hier immer erreichbar:',
    callUs: 'Ruf uns an:',
    phoneNumber: '0157 / 578 987 32',
    writeAMail: 'oder schreib eine Mail:',
    mail: 'shoop@devoop.de',
  },
  english: {
    contactTitle: `We're always here for you!`,
    contactDescription: `You have something on your heart? Let us know and write us a Message. Simply fill out the form below and off you go to Post!`,
    emailTitle: 'E-mail adress',
    emailPh: 'Your e-mail adresse...',
    fornameTitle: 'forname',
    fornamePh: 'forname',
    surnameTitle: 'surname',
    surnamePh: 'surname',
    requestTitle: 'Your request',
    sendBtn: 'Send',
    serviceTitle: 'Customer service',
    serviceSubtitle: 'None of that worked?',
    secSubtitle: 'We are always available here:',
    callUs: 'Call us:',
    phoneNumber: '0157 / 578 987 32',
    writeAMail: 'or write an e-mail:',
    mail: 'shoop@devoop.de',
  },
};
